# Generated by Django 4.2.6 on 2023-11-22 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0003_remove_question_answers_remove_task_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_uid', to='quiz_craft.task')),
            ],
        ),
    ]
