# Generated by Django 4.2.6 on 2023-11-22 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0004_taskuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_craft.userprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_craft.task')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_craft.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_craft.question')),
                ('task_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_craft.taskresponse')),
            ],
        ),
    ]
