# Generated by Django 4.2.6 on 2023-11-22 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0005_taskresponse_questionresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='task_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='quiz_craft.taskresponse'),
        ),
    ]
