# Generated by Django 4.2.6 on 2023-11-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0006_alter_questionresponse_task_response'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskresponse',
            unique_together={('profile', 'task')},
        ),
    ]
