# Generated by Django 4.2.6 on 2023-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0007_alter_taskresponse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(default='Maria', max_length=255),
        ),
    ]
