# Generated by Django 4.2.6 on 2023-11-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0008_userprofile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='text_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_craft.answer'),
        ),
    ]
