# Generated by Django 4.2.6 on 2023-11-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0009_questionresponse_text_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='text_answer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
