# Generated by Django 4.2.6 on 2023-12-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0010_alter_questionresponse_text_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SINGLEANSWER', 'Single Answer')], max_length=20)),
                ('min_win_grade', models.IntegerField()),
                ('player_weapon', models.CharField(choices=[('SWORD', 'Sword'), ('HAMMER', 'Hammer'), ('SCYTHE', 'Scythe')], max_length=20)),
                ('enemy_weapon', models.CharField(choices=[('SWORD', 'Sword'), ('HAMMER', 'Hammer'), ('SCYTHE', 'Scythe')], max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_craft.task')),
            ],
        ),
    ]
