# Generated by Django 4.2.6 on 2023-12-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0011_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_uid', to='quiz_craft.game')),
            ],
        ),
    ]
