# Generated by Django 4.2.6 on 2023-12-05 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_craft', '0013_questionresponse_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresponse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
